### ISSUE TITLE
Edit Bill

### ISSUE THREAD

**Issue by zernonia** [lyqht/Billy#12]
![Screenshot_20220624_204115_com lyqht billy](https://user-images.githubusercontent.com/59365435/175537982-0e9acf4f-75f4-455a-af2e-8dd6f31c1c0f.jpg)

I wanna edit the title/amount of the bill, but could not.

Device model: Huawei Nova 4

**Comment by lyqht** [comment]
Hi @zernonia , thanks for the feature request! This has not been worked on yet, and is part of the product roadmap. 
I'll get to this in the next release :)

**Comment by zernonia** [comment]
I couldn't find the roadmap, so not sure is it a bug 😂

* I clicked the `roadmap.md` in the readme 
![image](https://user-images.githubusercontent.com/59365435/175538659-10cd0981-94d7-4046-892e-78a2366fa4a6.png)

**Comment by lyqht** [comment]
Ah okay! I must have forgotten to update the main README.md, updated it to match the CONTRIBUTING.md. Thanks for highlighting!
